### ISSUE TITLE
Master issue for V3

### ISSUE THREAD

**Issue by son-link** [son-link/Skeleton#1]
This is the master issue for proposing additions for the future 3 version

- [x] Add fix to use Material Icons
- [x] Add small buttons class
- [ ] Add minimalice versions of skeleton and normalize
- [ ] Add classes for colors use the http://clrs.cc/ palette
- [ ] Add fix for other Font Icons (as Awesome Font, Fontello, etc)
